import type { Metadata } from "next";
import "./globals.css";
import { AppProvider } from "@/context/AppContext";
import { Toaster } from "react-hot-toast";
import { SocketProvider } from "@/context/SocketContext";

export const metadata: Metadata = {
  title: "Chat App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
      <body>
        <AppProvider>
          <SocketProvider>
            {children}
          </SocketProvider>
          <Toaster />
        </AppProvider>
      </body>
    </html>
  );
}
